baseURL = 'https://tft-display.net/'
languageCode = 'en-us'
title = 'TFT Display Technology'

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
